### ISSUE TITLE
URL-Resolver for FormWizzardEntry not working

### ISSUE THREAD

**Issue by ProfessorLogout** [barseghyanartur/django-fobi#102]
Hello,

generation of URLs via the method get_absolute_url on the model FormWizzardEntry[1] seems to be broken.
I would probably think it is broken because reverse gets called with kwargs={"slug": ***} and the url expects a key of "form_wizard_entry_slug".

Versions used: latest fobi from PyPI, django 1.11 and Python 3.5

Django Console Output:
django.urls.exceptions.NoReverseMatch: Reverse for 'fobi.view_form_wizard_entry' with keyword arguments '{'slug': 'test01'}' not found. 1 pattern(s) tried: ['formulare/wizard-view/(?P<form_wizard_entry_slug>[\\w_\\-]+)/$']

[1]
https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/models.py#L317

**Comment by barseghyanartur** [comment]
@ProfessorLogout:

Thanks for reporting this.

**Comment by barseghyanartur** [comment]
Solved in 0.12.6.
