### ISSUE TITLE
Show received data on success page

### ISSUE THREAD

**Issue by sliwowitz** [barseghyanartur/django-fobi#126]
I need to include data posted by the form in the success page (in a legacy app using older 0.5 Fobi version) so that the visitor can see the posted data, and I could generate a link to a payemnt site based on this information, but it's unclear to me how to do it. I see no way to include the posted result from the admin interface. I thought that the HTTP repost might do the trick, but that only contacts the other endpoint and doesn't replace the success page.

What is the preferred way to do this?

**Comment by barseghyanartur** [comment]
Are you using fobi with CMS? Or just as is?

**Comment by sliwowitz** [comment]
It's on django-cms 3.1.3

**Comment by barseghyanartur** [comment]
OK. Look, it's not very obvious, but you could use form_callbacks to store the submitted data into session (for the user) and show the session data in the thank_you template. It's gonna be very easy this way.

**Comment by barseghyanartur** [comment]
@sliwowitz:

Please, let me know if it worked for you, so that I can close the issue.

**Comment by barseghyanartur** [comment]
Closing this for now. Feel free to write again.

**Comment by sliwowitz** [comment]
Thank you for the tip. I was off during the weekend, and I'm wokring on the implementation now, but I realized there is one more requirement I forgot about earlier - we need to generate a unique ID for the filled out form, which we are now saving to the database using the db_store handler plugin. That ID has to be then displayed to the visitor, and passed to the payment system. I thought that I would make a copy of the db_store plugin which would generate some user-friendly ID, or just return the saved form's PK, but I can't figure out, how to access or pass such information to the callback.

**Comment by sliwowitz** [comment]
I'm also thinking about going in a similar direction you proposed for the original problem: Generating the ID in a separate DB table with a callback in the CALLBACK_BEFORE_FORM_VALIDATION stage, injecting it into a hidden form field, saving it in the session, and showing it from the session in the thank_you template. 

What would you feel to be the "proper" way to handle this?

**Comment by barseghyanartur** [comment]
@sliwowitz:

See the documentation of the form callbacks.

http://django-fobi.readthedocs.io/en/0.12.14/#creating-a-form-callback

```python
 def callback(self, form_entry, request, form):
```

``form_entry`` is one of the argument passed to the form callback. Thus, you could store that into the session.

By the way, form ``slug`` is unique too.

Regarding your second message, if your ID shall be unique for the entry submitted by the user, you might want to make a ``unique_id`` form field plugin, which would just generate a unique ID (for instance, based on ``uuid.uuid4``).

**Comment by sliwowitz** [comment]
Yes, I meant a unique ID for each submitted form - as in the order number. UUID won't look nice to the user, so I would just go with a simple incrementing integer, not too large as some users won't ude the online payment options, but will fill out this number directly when they do a wire transfer. That's why I think it would be better generated after the form was actually sent, so there wouldn't be many of them produced when the form is only displayed, but not filled out and sent.

**Comment by barseghyanartur** [comment]
@sliwowitz:

I see. In that case, you might do what you think is best.

Do you want to refer to the saved form data entries? In that case you might just want to make a custom DB store plugin.

https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_handlers/db_store/base.py

P.S.

I also provide limited "premium" support (I work on your product for making fobi work for you). Mail me for details.

**Comment by sliwowitz** [comment]
Thanks a lot for your help. In the end, I went with a helper model to generate sequential integer ids:
```python
from django.db import models
class IdHelper(models.Model):
    pass
```
The ID is generated in a callback after the rest of the form is validated, injected into a hidden form field, and sent to the session:
```python
from fobi.constants import CALLBACK_FORM_VALID_BEFORE_SUBMIT_PLUGIN_FORM_DATA
from fobi.base import FormCallback, form_callback_registry
from custom_fobi.models import IdHelper

FORM_SLUG = 'registration-form'
ID_FIELD_NAME = 'id'

class GenerateIdCallback(FormCallback):
    """Callback to generate submission ID."""
    stage = CALLBACK_FORM_VALID_BEFORE_SUBMIT_PLUGIN_FORM_DATA
    def callback(self, form_entry, request, form):
        if form_entry.slug == FORM_SLUG:
            id_helper = IdHelper.objects.create()               # Use database auto-increment field to generate a unique integer ID
            form.cleaned_data[ID_FIELD_NAME]  = id_helper.pk    # Inject the generated ID into the form
            request.session['order_id'] = id_helper.pk          # Store the ID in the user's session

form_callback_registry.register(GenerateIdCallback)
```

The form is then saved using the db_store handler. On the "thank you" page, I read the ID from the session, and retrieve the form from the DB store using a templatetag 
```django
{% get_saved_form_field form_id request.session.order_id 'field_name' %}
```
which takes the form's ID, and the generated submission ID:
```python
from fobi.contrib.plugins.form_handlers.db_store.models import SavedFormDataEntry
import simplejson as json

register = template.Library()
ID_FIELD_NAME = 'order_id'

def get_form_data(form_entry_id, submission_id):
    sstr1 = '"' + ID_FIELD_NAME + '": ' + str(submission_id) + ','  # Look for the ID value in the json text field
    sstr2 = '"' + ID_FIELD_NAME + '": ' + str(submission_id) + '}'  # It might be the last field in the set
    try:
        saved_form = SavedFormDataEntry.objects.get(form_entry_id=form_entry_id, saved_data__contains=sstr1)
    except SavedFormDataEntry.DoesNotExist:
        try: 
            saved_form = SavedFormDataEntry.objects.get(form_entry_id=form_entry_id, saved_data__contains=sstr2)
        except SavedFormDataEntry.DoesNotExist:
            return None
    return json.loads(saved_form.saved_data)

@register.simple_tag
def get_saved_form_field(form_entry_id, submission_id, field_name):
    data = get_form_data(form_entry_id, submission_id)
    if data==None:
        return "<b>There was an error saving your registration. Please, contact us at mail@example.com</b>"
    return data[field_name]
```
The DB lookup in the json-encoded text field doesn't feel elegant, but so far it seems to work.

**Comment by barseghyanartur** [comment]
@sliwowitz:

I'm glad it worked for you. Thanks for sharing. Worths a blog post. :)
