### ISSUE TITLE
Invisible recaptcha

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-fobi#127]
Implement invisible recaptcha as a fobi form field plugin based on this [pull request](https://github.com/barseghyanartur/django-fobi/pull/117/files).

- [x] Make a fobi invisible recaptcha plugin (in ``fobi/contrib/plugins/form_elements/security``).
- [x] Make correspondent widget for bootstrap3 theme.
- [x] Make correspondent widget for foundation5 theme.
- [x] Make correspondent widget for simple theme.
- [x] Make correspondent widget for django-cms-admin-style theme.
- [ ] Add tests.
- [x] Add documentation.
- [x] Clean up unused code.

WIP in branch [invisible-recaptcha](https://github.com/barseghyanartur/django-fobi/tree/invisible-recaptcha).

**Comment by barseghyanartur** [comment]
@minusf:

This is how I see it. It should not be difficult. If you feel like working on it, please go on (and feel free to ask me for help). 

If you don't have time (or don't feel like doing it), I will implement it one day soon (in the coming months).

**Comment by barseghyanartur** [comment]
@minusf:

It's almost done. Could you check if it works for you?

**Comment by minusf** [comment]
the javascript links are not picked up for the field for me...

**Comment by barseghyanartur** [comment]
Released in 0.12.16.
