### ISSUE TITLE
invisible recaptcha is broken

### ISSUE THREAD

**Issue by minusf** [barseghyanartur/django-fobi#144]
https://github.com/barseghyanartur/django-fobi/blob/41f48b8954e6335dbc05d49492d2f8924e71712f/src/fobi/contrib/plugins/form_elements/security/invisible_recaptcha/static/invisible_recaptcha/fobi.plugin.invisible_recaptcha.js#L26

this line brakes the invisible recaptcha.

`jquery.js:2 Uncaught Error: type property can't be changed`

what is the purpose of this line?

**Comment by barseghyanartur** [comment]
@minusf:

The snippet from Google used button without "type".

It worked for me though at the time of development. What browsers have you tested it with?

**Comment by minusf** [comment]
firefox and chrome.  it is jquery version dependent and jquery refuses this change because of IE if i am not mistaken

**Comment by barseghyanartur** [comment]
@minusf:

Just tested in:

- Google Chrome 64.0.3282.119 (Official Build) (64-bit)
- Firefox 58.0 (64-bit)
- Opera 50.0.2762.67

Worked for me. 

However, for older version of jQuery you could probably use some other code (or remove it, if it doesn't matter). Fobi is loosely coupled. Currently, the `src.fobi.contrib.themes.bootstrap3.widgets.form_elements.invisible_recaptcha_bootstrap3_widget.fobi_form_elements.InvisibleRecaptchaWidget` uses the `src.fobi.contrib.plugins.form_elements.security.invisible_recaptcha.widgets.BaseInvisibleRecaptchaWidget`, which loads the `src/fobi/contrib/plugins/form_elements/security/invisible_recaptcha/static/invisible_recaptcha/fobi.plugin.invisible_recaptcha.js` plugin. So, what you need is to copy the `src.fobi.contrib.themes.bootstrap3.widgets.form_elements.invisible_recaptcha_bootstrap3_widget` module locally, make changes to the JS and replace the `fobi.contrib.themes.bootstrap3.widgets.form_elements.invisible_recaptcha_bootstrap3_widget` app with your custom one in the settings.py.

**Comment by barseghyanartur** [comment]
Feel free to reopen.
