### ISSUE TITLE
Encoding issues with MailHandler (PY2)

### ISSUE THREAD

**Issue by adrien-delhorme** [barseghyanartur/django-fobi#150]
In PY2, the MailHandler fails when a form label contains non ASCII characters, because `send_mail` tries to encode in UTF-8 an already ASCII encoded `str`. `send_mail` should receive `unicode` or UTF-8 encoded `str`. 

The problem comes from the `safe_text` function that return `str` in PY3 but returns `str` in PY2 instead of `unicode`.
Maybe you should remove `.encode('utf-8')` or use django's `smart_text` instead of  `safe_text`?

https://github.com/barseghyanartur/django-fobi/blob/566f1600701b6c84069db4f141d78f15776ceb13/src/fobi/helpers.py#L113

In addition several strings are missing the `u"..."` prefix so they are `unicode` in PY3 but `str` encoded in ASCII in PY2 (because there is no encoding declaration at the top of the files and PY2 defaults to ASCII encoding).

https://github.com/barseghyanartur/django-fobi/blob/566f1600701b6c84069db4f141d78f15776ceb13/src/fobi/contrib/plugins/form_handlers/mail/mixins.py#L66

**Comment by adrien-delhorme** [comment]
Hello,

I also discovered that the encoding causes problems on form fields edit page. When a field has accentuated characters in its label, it is impossible to edit, delete or save the order of fields.

A screenshot that shows the missing buttons and field type (Text) in label, for the field that contains accentuated character:
![capture d ecran 2018-02-23 a 12 06 55](https://user-images.githubusercontent.com/1597706/36591452-59be58d2-1892-11e8-8a0e-200930444055.png)

**Comment by barseghyanartur** [comment]
@adrien-delhorme:

Thanks. Just checking, you're using Python 2, right?

**Comment by adrien-delhorme** [comment]
Yes, Python 2.7.9.

**Comment by barseghyanartur** [comment]
@adrien-delhorme:

Thanks! I'll fix it soon.

**Comment by barseghyanartur** [comment]
@adrien-delhorme:

Could you check if 0.12.20 works for you?

**Comment by adrien-delhorme** [comment]
@barseghyanartur It seems to work. Thanks!
