### ISSUE TITLE
public_key is required in django captcha

### ISSUE THREAD

**Issue by avdata99** [barseghyanartur/django-fobi#157]
In Django-recaptcha the [public_key is requered](https://github.com/praekelt/django-recaptcha/blob/develop/captcha/widgets.py#L21)
I guess we need something like `ReCaptchaWidget(public_key=settings.RECAPTCHA_PUBLIC_KEY, attrs=widget_attrs)` [here](https://github.com/barseghyanartur/django-fobi/blob/stable/src/fobi/contrib/plugins/form_elements/security/recaptcha/base.py#L100)

I'm getting this error after add ReCaptcha to any form
![imagen](https://user-images.githubusercontent.com/3237309/36561714-57610b9c-17f3-11e8-84ab-70a126c229b2.png)

**Comment by barseghyanartur** [comment]
@avdata99:

You're right. I quickly checked the source. There have been a backwards incompatible change somewhere in django-recaptcha 1.2.0.

https://github.com/praekelt/django-recaptcha/blob/1.2.0/captcha/widgets.py#L16

Thank you!
