### ISSUE TITLE
Typo on import line in recaptcha plugin

### ISSUE THREAD

**Issue by adrien-delhorme** [barseghyanartur/django-fobi#165]
https://github.com/barseghyanartur/django-fobi/blob/1af90ae9e51c76c6eb77fdba617366ec0f0ddcff/src/fobi/contrib/plugins/form_elements/security/recaptcha/base.py#L6
SyntaxError: invalid syntax

**Comment by barseghyanartur** [comment]
@adrien-delhorme:

Thanks. Fixed in 0.13.1.
