### ISSUE TITLE
`django.conf.urls.patterns()` upcoming removal.

### ISSUE THREAD

**Issue by jmsfwk** [barseghyanartur/django-fobi#17]
`django.conf.urls.patterns()` was deprecated in [Django 1.8](https://docs.djangoproject.com/en/1.9/releases/1.8/#django-conf-urls-patterns) and will be removed in Dajngo 1.10.

Will Django 1.5 support as list of `django.conf.urls.url()`'s or is it time to drop support for 1.5 (on master)?

    \django-fobi\src\fobi\admin.py:424: RemovedInDjango110Warning: django.conf.urls.patterns() is 
    deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of 
    django.conf.urls.url() instances instead.
      name='bulk_change_form_handler_plugins'),

    \django-fobi\src\fobi\admin.py:395: RemovedInDjango110Warning: django.conf.urls.patterns() is
    deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of 
    django.conf.urls.url() instances instead.
      name='bulk_change_form_element_plugins'),

**Comment by barseghyanartur** [comment]
@jmsfwk:

Thanks for bringing this up. A tiny change. The main URL modules use modern URLs for a long time already. I just forgot to change it in the admin module as well. The 1.5 support could be dropped any time soon, but I rather leave it intact as long as it still works.

**Comment by barseghyanartur** [comment]
@jmsfwk:

Thanks. Version 0.5.19 contains the changes. PyPI is up to date.
