### ISSUE TITLE
Save and resume feature for wizards?

### ISSUE THREAD

**Issue by zdexter** [barseghyanartur/django-fobi#192]
What would be the easiest way to pull pending form data in the session backend, and skip to the appropriate template in the wizard view?

**Comment by barseghyanartur** [comment]
@zdexter:

Look, the `get_form_list` (src.fobi.wizard.views.dynamic.DynamicWizardView#get_form_list) is responsible for generating the list of forms. I think `self.request` shall be generally available, so reading session data shouldn't be an issue.

You might want to override `process_step` (src.fobi.wizard.views.dynamic.DynamicWizardView#process_step) method and put your custom post-form session-affecting logic here.

**Comment by barseghyanartur** [comment]
P. S.

Since it might be a useful case for some other devs, I encourage you to document your development process and write an article on how you solved issue. Gist or own blog is ok. I'll add it to the wiki.

**Comment by barseghyanartur** [comment]
@zdexter:

That would be another way of doing that. I once thought about extending REST framework support for wizards, but didn't have time to implement that.

Are you planning to use [fobi for REST framework integration](https://django-fobi.herokuapp.com/api/fobi-form-entry/test-form-2/) or something else?

**Comment by zdexter** [comment]
@barseghyanartur yes, the fobi rest framework integration, along with a custom endpoints of some kind to allow saving partial progress at any point during the multi-step form, using a token generated on the frontend to lookup the progress later.

**Comment by barseghyanartur** [comment]
@zdexter:

Ok. If you plan to work with JSON schema, have in mind, that [JSON schema support hasn't been finialized yet](https://github.com/barseghyanartur/django-fobi/issues/69). Any help with that is greatly appreciated. It's just matter of naming, naturally, but I didn't get time to put my hands on it yet.

**Comment by barseghyanartur** [comment]
Closing this for now.
