### ISSUE TITLE
Update documentation (having Django 1.11 in mind)

### ISSUE THREAD

**Issue by cdvv7788** [barseghyanartur/django-fobi#194]
For example, in the context processors bit, the instructions given are for Django 1.7/1.8. The instructions should be updated to newer versions.

**Comment by barseghyanartur** [comment]
@cdvv7788:

That should certainly be done. For the moment, check the [example settings](https://github.com/barseghyanartur/django-fobi/blob/master/examples/simple/settings/base.py) as they support Django versions from >=1.8 to <=2.0.

**Comment by barseghyanartur** [comment]
Done.
