### ISSUE TITLE
Is there a way to render forms without the theme?

### ISSUE THREAD

**Issue by cdvv7788** [barseghyanartur/django-fobi#195]
The package gives a nice functionality, but when it comes to integrating into an existent site it is not easy.
I have a site already, and I want to display forms inside of it using the structure I already have. I don't need the users to be able to see anything beyond the form (the entries, the navbar, etc).
I tried to adapt it, but it is quite easy to break things.
What I would like is to have the capability of creating forms and wizards (using current views) and having the option to display it anywhere. Maybe providing a mixin that can interpret these forms and ease the work?

I don't know if something like that exists, but it would be useful as integrating this should be easier.

**Comment by barseghyanartur** [comment]
@cdvv7788:

What is your current site based on? Bootstrap 3? Foundation 5?

Building theme from scratch could cost you some time. However, you could instead try to make a theme based on Bootstrap 3 and simply plug it in.

Do I understand you correctly that you simply want to manage forms yourself and not let other users touch them? Describe your use-case (briefly) and I'll try to give a good advice.

**Comment by cdvv7788** [comment]
@barseghyanartur My theme is based on bootstrap3. I have for example a title below the navbar, that in my main theme is outside of the content block. The available themes, however, insert the title in the content block, using different classes.
I was able to adapt some of the bootstrap3 theme files to work with my theme, but that rendered useless some other pages of the package. I am pretty sure that I can fix them, but it is a pretty small change and took me a while to perform it.
My use case is pretty common, I think. I just want a way to create forms from the backend (you nailed that part, that is quite easy to work with imho) and to display them anywhere I want. I don't want anyone that is not authenticated to see it, and those that see my forms should see nothing but the form.
Think of formidable in wordpress (If you have worked with that). You create the forms in the admin, then embed the form with a shortcode, and it just works. You have a form, anywhere you want. The difference is obviously that in wordpress you add the shortcodes in content, while in here (non-cms case) you could provide a mechanism to add it with code (maybe a templatetag?).

**Comment by barseghyanartur** [comment]
@cdvv7788:

If it's about displaying forms anywhere you want, I would suggest you pick simplest CMS from them all - FeinCMS and use Fobi widget. In all CMS integrations, you can choose whether do or not show the form title, etc.

**Comment by barseghyanartur** [comment]
@cdvv7788:

If you decide to continue with fobi, it could be useful for others if you, as newcomer, would document your efforts (perhaps in a form of a blog post). I would repost it in wiki here then.

**Comment by cdvv7788** [comment]
@barseghyanartur I gave up on trying to update the templates directly before creating the issue. Without that, what I did does not amount to more than just installing the package, which imho is not enough for a decent post.
I may give it another try when I need something similar and I am using a CMS, but for now, this is it.
Thanks for the fast replies!
