### ISSUE TITLE
render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by nicolasmendoza** [barseghyanartur/django-fobi#196]
On Django 2.0.6 and Python 3.6.5, I'm getting the error "render() got an unexpected keyword argument 'renderer'" when I tried to add a new form or edit a existing form (loaded via data migration). Any idea ?

/fobi/templates/fobi/generic/snippets/form_properties_snippet.html

![error](https://user-images.githubusercontent.com/9975193/43802975-d2aa32e0-9a6d-11e8-92a2-bab967f5ae11.png)

**Comment by nicolasmendoza** [comment]
`Support for Widget.render() methods without the renderer argument is removed.` on django 2.1 but I'm using django 2.0.6. Hmmm

**Comment by nicolasmendoza** [comment]
Updated. This issue is in Django 2.1. My fault with the environments. When I up my app on dev mode is taking django 2.1 and not 2.0.6. So, the issue have sense but I'm using a incorrect django version for me. So I'm fix this locally because I need django 2.0.6 no 2.1.

**Comment by barseghyanartur** [comment]
@nicolasmendoza:

Thanks for the update.

Btw, support for Django 2.1 is planned.

**Comment by barseghyanartur** [comment]
@nicolasmendoza:

FYI, implemented in 0.13.4.
