### ISSUE TITLE
Problem with Django-autoslug using Django 2.1

### ISSUE THREAD

**Issue by enriquemt** [barseghyanartur/django-fobi#198]
I have installed an work locally using Quickstart guide and modifying manually Autoslug library in my .virtualenv folder because I got an error using 

I have checked and with django 2.1 fobi should install django-autolug-iplweb however when I check the Pipfile.lock it is installing django-autoslug 1.9.3.

Locally my app works fine because I modified Autoslug lib, however when I try to deploy in Heroku I got the error agaoin, because it is using the original library, any ideas how can I solve this? Thanks in advance.

![image](https://user-images.githubusercontent.com/1184775/44200651-67249200-a147-11e8-827b-ef1dfb5de600.png)

**Comment by barseghyanartur** [comment]
That's strange. I think I replaced original autoslug with iplweb version everywhere for all modern versions of dkango. In any case, I have a demo running on heroku with no issues. Check project wiki for details.

**Comment by enriquemt** [comment]
Yes, that's what I thought after reviewing the wikis however I just followed the Quickstart guide and installed using "pip install django-fobi" in my virtualenv where previously I installed  django 2.1.

If I check in my Pipfile.lock file the autoslug call instead of autoslug-iplweb appears...

![image](https://user-images.githubusercontent.com/1184775/44201959-ebc4df80-a14a-11e8-8ed7-0857e198e627.png)

**Comment by barseghyanartur** [comment]
@enriquemt:

I have completely removed any presence of ``django-autoslug`` from Python code (setup.py). Use version 0.13.6.

**Comment by enriquemt** [comment]
Thanks a lot
