### ISSUE TITLE
TypeError at /fobi/forms/create/

### ISSUE THREAD

**Issue by hernanfila** [barseghyanartur/django-fobi#201]
Hi, I am getting next error:
render() got an unexpected keyword argument 'renderer'

This is the information I got:
`
Exception Location: | /home/myuser/myEnvironments/my_django_env/lib64/python3.6/site-packages/django/forms/boundfield.py in as_widget, line 93
`

Python Version: | 3.6.5

`my_django_env/lib64/python3.6/site-packages/fobi/templates/fobi/generic/snippets/form_snippet.html, error at line 57`

Last part of traceback:

```
File "/home/myUser/myEnvironments/my_django_env/lib64/python3.6/site-packages/django/forms/boundfield.py" in __str__
  33.         return self.as_widget()

File "/home/myUser/myEnvironments/my_django_env/lib64/python3.6/site-packages/django/forms/boundfield.py" in as_widget
  93.             renderer=self.form.renderer,

Exception Type: TypeError at /fobi/forms/create/
Exception Value: render() got an unexpected keyword argument 'renderer'
```

Anything else you need please tell me. 

Thank you

**Comment by barseghyanartur** [comment]
@hernanfila:

Which version of django-fobi are you using?

**Comment by hernanfila** [comment]
I uninstalled ckeditor and last error was gone(pip uninstall django-ckeditor) . If you need additional information for the original inquiry, please tell me. I keep using django 2.0.8.

Thanks!

**Comment by barseghyanartur** [comment]
@hernanfila:

[Demo](http://django-fobi.herokuapp.com/en/fobi/) is currently running on `Python` 3.6, `Django` 2.1 and `django-ckeditor` >= 5.6.0.

The full list of demo requirements:

```
bleach==1.5.0
Django>=2.1,<2.2
SQLAlchemy==0.9.8
dj-database-url==0.5.0
django-postgrespool==0.3.1
gunicorn==19.9.0
psycopg2==2.7.5
whitenoise==4.0
ipython

MarkupSafe
django-fobi==0.13.5
django-admin-tools>=0.8.1
django-autoslug-iplweb
django-ckeditor>=5.6.0
https://github.com/marbont/django-codemirror-widget/archive/12bb692f805c47e5d418ae26be7e190f7138f364.zip
django-formtools>=2.1
django-nine>=0.1.10
django-nonefield>=0.3
django-registration-redux>=2.4
easy-thumbnails>=2.5.0
ordereddict>=1.1
simple-timer>=0.2
vishap>=0.1.5

django-simple-captcha>=0.5.7
mailchimp

django-admin-timeline>=1.6.1

FeinCMS==1.13.6
django-mptt==0.9.1

djangorestframework==3.8.2
```

Additionally, see the [example requirements for Django 2.1](https://github.com/barseghyanartur/django-fobi/blob/master/examples/requirements/django_2_1.txt).

Since that works, it would be good if you could find out where the problem is. I can't reproduce it locally or on demo.

**Comment by barseghyanartur** [comment]
@hernanfila:

Did you manage to solve your problem? If so, it would be useful to leave a couple of remarks here (for other folks who might experience similar issues in future).

**Comment by hernanfila** [comment]
Hi @barseghyanartur, this is what I added in settings.py, and error was gone: SITE_ID= 1.
I am not pretty sure why it solved it, but it did it. 

Thank you for your follow-up!
