### ISSUE TITLE
Select multiple element

### ISSUE THREAD

**Issue by hernanfila** [barseghyanartur/django-fobi#202]
Hi @barseghyanartur ,
I am getting an issue when selecting more than one item in the select multiple element:

![image](https://user-images.githubusercontent.com/1685461/47862377-be93df00-ddd3-11e8-81e8-9dd30c3cf417.png)

Select one or more:
![image](https://user-images.githubusercontent.com/1685461/47862471-f69b2200-ddd3-11e8-9368-043589c0a904.png)

In the server, I want to read selected values, but it seems to be taking only one item:
When I print request.POST.dict(), I see only one value in the select Multiple field.

Do you know how can I get all selected values? 

Thank you

**Comment by barseghyanartur** [comment]
@hernanfila:

You're doing it in a wrong way. Check this:

- [form handler usage](https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_handlers/db_store/base.py#L50)
- [form callback usage](https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_handlers/db_store/callbacks.py#L37)
- [documentation](https://github.com/barseghyanartur/django-fobi#creating-a-new-form-handler-plugin)

**Comment by hernanfila** [comment]
Thank you for the information. Now I am working with cleaned_data. But in the multi-selection, if I print cleaned_data, I can see ['selected 1', 'selected 2'] but it's filled with their names and not their ID's. I think it should be ['selected1Id', 'selected2Id']. I mean, the option that I completed in the form element:
![image](https://user-images.githubusercontent.com/1685461/47918632-e47cba80-de8b-11e8-9663-b8d0b8dff61a.png)


Thank you and sorry to bother you.

**Comment by barseghyanartur** [comment]
@hernanfila:

FYI, https://github.com/barseghyanartur/django-fobi/tree/stable/src/fobi/contrib/plugins/form_elements/fields/select_multiple/

```
By default, the submitted form value of select_multiple elements is label (human readable representation of the value chosen). However, that part of the behaviour has been made configurable. You can choose between the following options:

Consider the following list of (value, label) choices (the first element in the tuple is value, the second element is label):

[
    ('alpha', 'Alpha'),
    ('beta', 'Beta'),
    ('gamma', 'Gamma'),
]
- "val": `value` (example: "alpha").
- "repr" (default): `label` (example: "Alpha").
- "mix": `value (label)` (example: "Alpha (alpha)").

Simply set the FOBI_FORM_ELEMENT_SELECT_MULTIPLE_SUBMIT_VALUE_AS assign one of the following values: "val", "repr" or "mix" to get the desired behaviour.
```

That applies to all multi-value plugins.
