### ISSUE TITLE
Page not found after successful installation

### ISSUE THREAD

**Issue by testaccountsnt** [barseghyanartur/django-fobi#210]
I am trying to deploy django-fobi on my ubuntu 16.04. I have download the sh file which is mentioned in README.rst and executed it. It installed all packages finished installation with  

System check identified no issues (0 silenced).
April 15, 2019 - 07:51:46
Django version 1.9.13, using settings 'settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.

When I try to open site in browser as per instruction, it gives me page not found.
I tried

    URL: http://127.0.0.1:8001/fobi/
    URL: http://127.0.0.1:8001/admin/

Both urls are showing error  'page not found'. There was no error in complete installation process, still I am getting this issue.
Please help me to solve this.

Thank you.

**Comment by barseghyanartur** [comment]
@testaccountsnt:

Perhaps it's `/en/fobi/` and `/en/admin/`, like in [heroku demo](https://django-fobi.herokuapp.com/).

**Comment by testaccountsnt** [comment]
Thank you, it worked. It was really foolish issue but I could not manage to think on this line.
I was just following readme blindly.
Thanks again
