### ISSUE TITLE
[Installation Broken] ModuleNotFoundError: No module named 'nine.versions'

### ISSUE THREAD

**Issue by nicolasmendoza** [barseghyanartur/django-fobi#219]
[Installation Broken], using:

Python 3.7
Django                                     2.1.5
django-fobi                               0.13.10
django-nine                              0.2 (fobi dependency)

- Traceback message:
`from nine.versions import DJANGO_GTE_1_10`
`ModuleNotFoundError: No module named 'nine.versions'`

- Code:
/fobi/models.py L.13

`from nine.versions import DJANGO_GTE_1_10`

**Comment by barseghyanartur** [comment]
Pin 'django-nine' to 0.1.3

**Comment by nicolasmendoza** [comment]
Would be nice to freeze the library (Fobi dependencies) versions or try to be more explicit in setup.py to avoid issues on this kind. Because this was working but looks like the issue is with the latest version of the nine's library (v2.0, released 1 day ago).

A temporal workaround is to override the nine-version installed by Fobi, the version 0.1.13 instead of version 0.2

**Comment by barseghyanartur** [comment]
I'll fix that today. One way or another.

**Comment by nicolasmendoza** [comment]
Thanks @barseghyanartur

**Comment by barseghyanartur** [comment]
@nicolasmendoza:

It shall be fixed by now. If you install it again (in a new environment) or upgrade `django-nine` to latest version (0.2.1).

**Comment by nicolasmendoza** [comment]
Thanks @barseghyanartur
