### ISSUE TITLE
Does fobi allow the end user to add form elements dynamically?

### ISSUE THREAD

**Issue by jeromecc** [barseghyanartur/django-fobi#224]
Hi!
So for instance if I want to collect 5 or more (let's say up to 20) textual answers (CharField), is it possible to display 5 fields and a + sign to add a 6th field, then maybe a 7th etc? So that I don't clutter the page with 20 fields while most respondents will only use 5 or 6.
Thanks.

**Comment by barseghyanartur** [comment]
You could certainly do it with javascript.

**Comment by barseghyanartur** [comment]
I would solve that issue in the following way (if I understand you correctly):

- You create your form with 10 fields.
- You assign a custom template to your form.
- That template shall add a unique ID for your conditional custom JavaScript.
- Your JavaScript shall only show 5 fields at once allowing to show more when + sign is clicked on.
- Somehow you shall store your clicks somewhere in local storage (for when form is incomplete and you need to reload the page).
