### ISSUE TITLE
broken thumbnails, easy_thumbnails dep out of date

### ISSUE THREAD

**Issue by minusf** [barseghyanartur/django-fobi#237]
Please bump the `easy_thumbnails` dependency, `2.4.1` breaks thumbnail generation.

```
AttributeError("'FileSystemStorage' object has no attribute 'modified_time'")
```

**Comment by barseghyanartur** [comment]
@minusf:

Aggressive pinning should not be necessary. For now it's pinned to everything greater than or equal to `2.4.1`. Like that, package safely [passes tests](https://travis-ci.org/github/barseghyanartur/django-fobi/builds/664134627?utm_source=github_status&utm_medium=notification) for range Django 1.11 to 3.0.

Test requirements, however, do have their own pinned versions (which resolves nicely).

- [Django 3.0](https://github.com/barseghyanartur/django-fobi/blob/master/examples/requirements/django_3_0.txt)
- [Django 2.2](https://github.com/barseghyanartur/django-fobi/blob/master/examples/requirements/django_2_2.txt)
- [Django 1.11](https://github.com/barseghyanartur/django-fobi/blob/master/examples/requirements/django_1_11.txt)
