### ISSUE TITLE
Custom exporter

### ISSUE THREAD

**Issue by mick88** [barseghyanartur/django-fobi#24]
I would like to suggest adding the option to write custom form exporter. At the moment it's inly possible to export to a proprietary json format. 
In my case, I'm using FoBi to enable non-technical users to build data models which I'd like export as Django models (python code). I wrote an exporter, but there's no simple way to hook it up to the export page in the template.

**Comment by barseghyanartur** [comment]
@mick88:

Look, there are different kinds of exports in `django-fobi`.

1) Export of form definitions.
2) Export of form data.

Which of the above mentioned two is your case?

**Case 1**

The original purpose of exporting the form definitions was to give users ability to import them into `django-fobi` later on or "freeze" versions for some reason. AFAIK, there is no standard way/format that could be applied to save the form definitions.

I would eventually accept a neat pull request regarding the change. Or even add the feature to the list of long-term TODOs. But that won't happen any time soon (in coming 6 months).

But a more direct and straight-forward solution of your issue would be just to add a couple of lines of code to your `django-fobi` templates.

https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/templates/fobi/generic/dashboard.html#L54

You could add there something like:

```html
<li>
  <a href="{% url 'fobi.your_own_export_form_entry' form_entry.pk %}">
    <span class="glyphicon glyphicon-export"></span> {% trans "Your own export" %}
  </a>
</li>
```

Same could be applied to the following template:

https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/templates/fobi/generic/edit_form_entry_ajax.html#L175

**Case 2**

If you need to be able to export form data into some custom format, you simply need to make another form handler plugin. Currently [db_store](https://github.com/barseghyanartur/django-fobi/tree/master/src/fobi/contrib/plugins/form_handlers/db_store) plugin is used. It contains [the code](https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_handlers/db_store/views.py#L65) to save the form data entries into CSV format. If you need to save them into Python format instead, you better make a new form handler plugin (for instance, `pycode_store`) and [register](https://github.com/barseghyanartur/django-fobi#creating-a-new-form-handler-plugin) it properly.

**Finally**

If you think community could benefit from your experience, publish your code somewhere and provide me with a link.

**Comment by barseghyanartur** [comment]
@mick88:

Can I close this?

**Comment by mick88** [comment]
I think so. I implemented my own exporting logic in my app, but it's not good enough to integrate it with fobi directly. If I decide to contribute my code, I can come back with a merge request.
