### ISSUE TITLE
django version check in theme templates not working

### ISSUE THREAD

**Issue by 0pt1c** [barseghyanartur/django-fobi#240]
I'm updating a project to Django 3.0 and posted a comment last week regarding an issue with `fobi` and deprecated import statements in the theme templates.

https://github.com/barseghyanartur/django-fobi/pull/214#issuecomment-608072628

I updated to 0.16.2 to get the newest code, but am still getting the error. I think the version check is not working correctly. You can see in the first screenshot I'm on django 3.0, and the second screenshot shows that the version check didn't load the right import.

![Screenshot from 2020-04-06 15-32-10](https://user-images.githubusercontent.com/2586233/78608358-0404d900-781e-11ea-9344-b5fd79af2637.png)

![Screenshot from 2020-04-06 15-32-45](https://user-images.githubusercontent.com/2586233/78608380-0bc47d80-781e-11ea-8b97-5183778d2390.png)

Additionally, this line in dashboard.html should probably be removed:

https://github.com/barseghyanartur/django-fobi/blob/1077c934cb0a0801ef6db6914f9ec4964da0c18d/src/fobi/contrib/themes/simple/templates/simple/dashboard.html#L6

**Comment by barseghyanartur** [comment]
Strange. I'll dig into it later today. Thanks for reporting.

**Comment by barseghyanartur** [comment]
@0pt1c:

Sorry for the buzz. Fixed in 0.16.4 by simple replace of the `admin_static` with `static` (since `static` is available in Django 1.11, which is the minimum supported version).

**Comment by 0pt1c** [comment]
@barseghyanartur thanks so much for the change and getting the new version out so quickly!
