### ISSUE TITLE
[Question] Is it possible to split plugin data in user friendly form fields in django admin?

### ISSUE THREAD

**Issue by KarimTayie** [barseghyanartur/django-fobi#241]
hello,
I want to split the plugin data field in django admin to a group of fixed-form fields (ex. label, name, help_text, initial, max_length, required, placeholder) with each plugin name. instead of typing them as JSON format.
is that possible?

**Comment by barseghyanartur** [comment]
You're not supposed to use django admin for that. You should be using the django-fobi management interface. See the screenshots section in docs.
