### ISSUE TITLE
getting form submission data in api

### ISSUE THREAD

**Issue by MySecondLanguage** [barseghyanartur/django-fobi#246]
Hi, I am going through trouble, I notice Django-fobi only returning API for form entry.

I am trying to extract all the user submission based form or wizard in API endpoint.

I have integrated the fobi drf_integration module but it only returns data related form entry.

Can anyone help me how can we get user submission data in API endpoint?

**Comment by barseghyanartur** [comment]
That part isn't available yet, but would be eady to implement. Would you have time to work on this?

**Comment by MySecondLanguage** [comment]
OK, I will work on this

**Comment by MySecondLanguage** [comment]
OK, I will work on it.  Can you please give me the model name where the submission is being populated?

I will implement this today

**Comment by barseghyanartur** [comment]
https://github.com/barseghyanartur/django-fobi/blob/v0.16.x/src/fobi/contrib/plugins/form_handlers/db_store/models.py

There it is. A couple of things. 

 - Form submissions are implemented as an add-on (optional). So it should stay. Devs would have to include a dedicated router urls in their urls.py in order for it to work.
 - Think of permissions. Owners of the form should be able to see submissions. No one else should.
 - Please implement your viewsets and serializers in the drf integration app: https://github.com/barseghyanartur/django-fobi/tree/v0.16.x/src/fobi/contrib/apps/drf_integration/form_handlers/db_store
 - Please use v0.16.x branch to fork from.

**Comment by MySecondLanguage** [comment]
OK, Thanks a lot
