### ISSUE TITLE
Same label name doesn't allow me to add?

### ISSUE THREAD

**Issue by saileshkush95** [barseghyanartur/django-fobi#249]
This is awesome project but my requirements is little bit different, it doesn't allow me to add same label name. for multiple fields

**Comment by barseghyanartur** [comment]
Could you be more specific? Why would you want the same label for different fields?

**Comment by saileshkush95** [comment]
Suppose I want to add full marks field for two subject. In both case i want to use marks field name instead of subject_one_marks and subject_two_marks, It is  just for random use case.

**Comment by barseghyanartur** [comment]
In theory, of course it's possible to add another field called `label_display` and show that text when rendering the form. However, I still think it's confusing.

Unfortunately, fieldsets are not supported (and likely they won't be, unless development is heavily sponsored). That makes having the same label on the same form unusable.

Contact me (email is in the readme) if you have a budget.

**Comment by saileshkush95** [comment]
sure,  but as for now its perfect and thank you for your works and maintaining this package
