### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by jbeck111** [barseghyanartur/django-fobi#255]
The demo is erroring out with Server Error (500) when a login is attempted with the credentials provided in the ReadMe.

**Comment by barseghyanartur** [comment]
Works now.

**Comment by Bashar** [comment]
> Works now.

went down again https://django-fobi.readthedocs.io/en/latest/#live-demo
https://django-fobi.herokuapp.com/

![image](https://user-images.githubusercontent.com/142219/151147834-ddd19f26-8d39-4c42-8971-e846207b9a6d.png)

**Comment by Bashar** [comment]
sometimes home loads but logging in at 
![image](https://user-images.githubusercontent.com/142219/151148641-f88aa502-6863-46d8-bf02-51fa77159783.png)

fires an error
