### ISSUE TITLE
Input field desabled

### ISSUE THREAD

**Issue by Aqurds** [barseghyanartur/django-fobi#268]
Hello,

Thanks for building this great project!

In Form building, I'm getting the input field remains disabled and read-only, when the disabled property is set to false as well as the read-only property.

https://imgur.com/a/7U6TmMi
Screenshots links are attached. Is it a bug?

Another thing is, that I am planning to make the "Export" & "Import" process automatic. Is there any way to bind these events on "form handler" plugins? Or any suggestions, please?

Regards,
Omar.

**Comment by barseghyanartur** [comment]
@Aqurds:

This looks strange. I've tested it all just a couple of days ago, and it worked well. Browser tests pass. Which versions are you using (Python/Django)?

Regarding `I am planning to make the "Export" & "Import" process automatic` - please explain in detail what do you need (and how do you want it to work).

**Comment by Aqurds** [comment]
Hi, @barseghyanartur thanks for your comment :) 

I am using
Python 3.7.9
Django==3.2.13

Regards

**Comment by Aqurds** [comment]
Regarding I am planning to make the "Export" & "Import" process automatic - please explain in detail what do you need (and how do you want it to work).

-- On submit event, the form handler is working under the hood, Is there any way we can export the form in JSON format as well (on submit event) by extending the form handler plugin or creating a new plugin?

**Comment by barseghyanartur** [comment]
@Aqurds:

I'm still missing a lot of details. What are you planning to do with the data in JSON format?

**Comment by barseghyanartur** [comment]
@Aqurds

As for `disabled` issue, check the [demo](https://github.com/barseghyanartur/django-fobi#demo). Does it work for you?

**Comment by Aqurds** [comment]
@barseghyanartur the plan on my side is quite deep, the first phase is to export the form. In the form list view, I see a button for exporting the form and it gives the facility to download the form in JSON format. https://imgur.com/a/NYO4lbK

The point here I am trying to get is, is there any way to bind this export feature with the form submit button? If it's not clear yet, then I will post a video explaining my thought.

Regards.

**Comment by Aqurds** [comment]
> 

Unfortunately, it doesn't work in the demo too. I just added an input field in a form from the demo and it remains disabled! https://imgur.com/a/S6aPgpX

**Comment by barseghyanartur** [comment]
@Aqurds:

You might be mixing things up. There are two types of exports here.

- Forms (how you design them, with all form elements, form handlers, etc) can be exported into JSON format and imported on other django-fobi instances (if you're using exactly same or near exactly same instances).
- Form submissions - the data users submitted when filling in a form created by fobi - is handled by the form handlers. ATM, db_store plugin has a couple of additional features, such as export to CSV or Excel.

Depending on what you need, the path would be different. If you work on a commercial project, I might be able to think along to help you to make the best of it. Send me an email, if that's the case.

As of the bug, I tested it with Chrome, Firefox, Opera and Brave. All works well. Which browser do you use? Try disabling add-ons or starting browser in incognito mode.

**Comment by barseghyanartur** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by jarrthur** [comment]
> Hi,
> 
> Input fields are disabled for me too. I tried it in Chrome Incognito mode on your live demo.
> 
> regards, dejan

I'm having this same problem too

**Comment by barseghyanartur** [comment]
@jarrthur:

Thanks for reporting this. Could you please include as much details as possible? Your operating system, browser version, etc.

**Comment by barseghyanartur** [comment]
FYI: It works for me.

System: Linux Ubuntu 22.04

Just tested on the following browsers: 

- Brave [Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)](https://brave.com/latest/)
- Firefox 114.0 (64-bit)

Can it be that you have some strange plugin installed?

**Comment by felixcheruiyot** [comment]
I'm getting this problem too. Looking into it. Once I find a fix I'll come back and update you.
