### ISSUE TITLE
can only concatenate list (not "tuple") to list on python 3.10.6 and django 4.1

### ISSUE THREAD

**Issue by ameenalakhras** [barseghyanartur/django-fobi#277]
running the latest package version (0.9.4) with python 3.10.6 and django 4.1 raised an error when strting the django server 

  File "/someproject/venv/lib/python3.10/site-packages/fobi/admin.py", line 651, in <module>
    class FormWizardHandlerAdmin(BasePluginModelAdmin):
  File "someproject/venv/lib/python3.10/site-packages/fobi/admin.py", line 654, in FormWizardHandlerAdmin
    actions = [
TypeError: can only concatenate list (not "tuple") to list 

it seems django actions is a tuple and django-fobi uses list in actions, combining the two raises the error "TypeError: can only concatenate list (not "tuple") to list "
a solution would be make the django-tobi action as tuple to solve the issue

it seems like it happens in multiple lines in the fobi/admin.py file, converting them to tuple solved my issue.

**Comment by barseghyanartur** [comment]
Django 4.1 is not yet supported. Will be soon.

**Comment by barseghyanartur** [comment]
Superseded by https://github.com/barseghyanartur/django-fobi/issues/278
