### ISSUE TITLE
Instantiating User in models.py can cause a circular import in Django <= 1.6

### ISSUE THREAD

**Issue by ItsNotWorking** [barseghyanartur/django-fobi#3]
Calling User = get_user_model() in models.py can cause a circular import if other packages also do so.

As ForeignKeys can be passed by reference a safer way to cover standard and custom user models would be something like:

    user_model_label = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

If you're looking for a more complete solution, django-cms covers all the bases in their implementation defined here https://github.com/divio/django-cms/blob/develop/cms/utils/compat/dj.py which is then used here https://github.com/divio/django-cms/blob/develop/cms/models/permissionmodels.py#L18

**Comment by barseghyanartur** [comment]
Hey,

Thanks for bringing this up. I'll check it asap.

Best regards,

**Comment by barseghyanartur** [comment]
You're absolutely right. The ``get_user_model`` should be applied on the function/method level. The settings.AUTH_USER_MODEL should be used when referencing the model in a foreign key or many-to-many relations.

- https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.get_user_model
- https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.get_user_model
- https://docs.djangoproject.com/en/1.6/topics/auth/customizing/#django.contrib.auth.get_user_model
- https://docs.djangoproject.com/en/1.5/topics/auth/customizing/#django.contrib.auth.get_user_model

Thanks again for bringing this up. The fix will come soon.

**Comment by barseghyanartur** [comment]
Fixed in 0.4.17.

**Comment by barseghyanartur** [comment]
Fixed in 0.4.17.

**Comment by ItsNotWorking** [comment]
No worries, thanks for the fix :)
