### ISSUE TITLE
Making fobi form creation django admin only.

### ISSUE THREAD

**Issue by geekashu** [barseghyanartur/django-fobi#30]
Hi,

I want form creation panel should only be visible via admin. If i use simple theme and "/admin/fobi" in edit urls i am able to get the feelling of django admin. But since i am using django-suit thus simple theme doesn't matches it up.

Also, can't we have fobi admin form "change form /add form" like the one we see outside the admin.

**Comment by barseghyanartur** [comment]
You should make a django-suit theme then. Take djangocms-theme as example.

**Comment by barseghyanartur** [comment]
A proper solution would be to make a custom theme for `django-suit`.

Pull requests are welcome.
