### ISSUE TITLE
Class based view dashboard can be reached by anonymous

### ISSUE THREAD

**Issue by sveetch** [barseghyanartur/django-fobi#300]
## Bug Report

**Expected behavior/code**

The class base view which implements the Dashboard should be reachable only from logged in user (at least).

**Actual Behavior**

Everyone can reach the dashboard when it has be mounted from class based view urls. Opposed to the old function view which correctly check for login required and permissions.

**Steps to Reproduce**
1. Install django-fobi and mount it using urls for class based views;
2. Run the Django server and without to be logged as an user, go to the fobi dashboard; 
3. You can reach the dashboard, fortunately it is empty from any data;

**Environment**
- System: Linux
- Python: 3.8.10
- Django: 4.0.8
- django-fobi: 0.19.4
 
**Possible Solution**

It seems pretty simple as adding the missing ``PermissionMixin`` inheritance, so just changing:

https://github.com/barseghyanartur/django-fobi/blob/8208893aed6930432d5ea8662bf7058d8165ed10/src/fobi/views/class_based.py#L242

To:

```
class DashboardView(PermissionMixin, ListView):
```

**Comment by barseghyanartur** [comment]
Thanks for reporting this. You're totally right. I think I missed that one.

**Comment by barseghyanartur** [comment]
@sveetch:

Released in 0.19.5.

**Comment by sveetch** [comment]
Nice responsiveness, thanks for the quick release  !
