### ISSUE TITLE
Can't find plugin widget with uid `simple.textarea`

### ISSUE THREAD

**Issue by geekashu** [barseghyanartur/django-fobi#31]
I am getting this in DEBUG logs for almost every elements i add through simple theme. 
`Can't find plugin widget with uid `simple.textarea` in `<class 'fobi.base.FormElementPluginWidgetRegistry'` though elements are added good and displayed. Is this intentional or am i missing some config?

**Comment by barseghyanartur** [comment]
@geekashu:

It's all fine. It's internal.
