### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by fabienheureux** [barseghyanartur/django-fobi#319]
Hey, I just discovered this project while considering building a Django form builder. 

Is this project still active ? Is it used in production somewhere ? 
It seems that no recent commits were pushed recently.

Thanks a lot for your work Artur, this project is impressive for an almost one-person project 👌

**Comment by barseghyanartur** [comment]
It's not actively developed anymore (since it's quite complete with features, but I try to keep up with Django updates.
As far as I know, it has been used in many production deployments, since 2014.
