### ISSUE TITLE
Element "name" field strips underscores

### ISSUE THREAD

**Issue by mick88** [barseghyanartur/django-fobi#33]
Underscores are allowed in name field.

When entering field label "Test Field", Name is populated with "test_field" and saves correctly.

However, when trying to enter "test_field" as name manually, the underscores are stripped-out and field name becomes one continuous word as soon as Name field is unfocused.

**Comment by barseghyanartur** [comment]
@mick88:

Confirmed. Added to the TODOs. Will be fixed in the upcoming release. Thanks!

**Comment by barseghyanartur** [comment]
@mick88:

Fixed in 0.6.9.
