### ISSUE TITLE
Quick start doc doesn't mention url inclusion for db_store form handler

### ISSUE THREAD

**Issue by thomasWajs** [barseghyanartur/django-fobi#4]
For the initial setup to work, the urls.py file should also add the line :
```
url(r'^fobi/', include('fobi.contrib.plugins.form_handlers.db_store.urls')),
```

Otherwise, it's impossible to use the handler. Step to reproduce :
 1. Folow the quick start setup
 2. Create a form
 3. Add a DB Store handler

A redirection to /form/edit/{id} occurs, with a NoReverseMatch exception:
```
Reverse for 'fobi.contrib.plugins.form_handlers.db_store.view_saved_form_data_entries' with arguments '(1,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

**Comment by barseghyanartur** [comment]
It does. Which version of the docs you are refering to?

http://pythonhosted.org/django-fobi/quickstart.html

**Comment by thomasWajs** [comment]
django-fobi.readthedocs.org/en/0.4.19/index.html#installation

**Comment by barseghyanartur** [comment]
@thomasWajs 

True. That part isn't covered in the general docs well. I did document it in the quick start though. But it's worth mentioning anyway. Thanks!

**Comment by thomasWajs** [comment]
Maybe you should remove duplication of the installation instruction, there is one on the index and one on the quickstart guide.

**Comment by barseghyanartur** [comment]
@thomasWajs 

Mentioned in the main docs as well. Thanks!
