### ISSUE TITLE
ProgrammingError raised when using the 'Export data to CSV/XLS' action

### ISSUE THREAD

**Issue by ababic** [barseghyanartur/django-fobi#45]
On the Heroku demo site, having selected some 'Saved form data entry' objects for export, then choosing the action from the actions drop-down at the top, a ProgrammingError is raised.

As attempted from:
https://django-fobi.herokuapp.com/en/admin/fobi_contrib_plugins_form_handlers_db_store/savedformdataentry/

**Comment by barseghyanartur** [comment]
@ababic:

Confirmed.

- https://django-fobi.herokuapp.com/en/fobi/plugins/form-handlers/db-store/export/592/

Thanks for reporting!

**Comment by ababic** [comment]
Thanks for picking this up so quickly.

**Comment by barseghyanartur** [comment]
@ababic:

Hey, btw, I saw you have wagtail experience. That's something `django-fobi` is still missing  - a `wagail_integration` contrib package. Would you be interested working on it?

**Comment by ababic** [comment]
@barseghyanartur Yes, that's certainly something I could create a PR for. Although, my spare time is mostly taken up with work on wagtail and wagtailmenus at the moment, so progress might be slower than you'd like.

**Comment by barseghyanartur** [comment]
@ababic:

Fixed in 0.9.6.
