### ISSUE TITLE
Add a `wagtail_integration` integration app for Wagtail support

### ISSUE THREAD

**Issue by ababic** [barseghyanartur/django-fobi#46]
Hi @barseghyanartur. Have had a look through the existing integration apps, and am confident I can create one for Wagtail easily enough. I've created this issue here to ask a few preliminary questions, if that's okay?

**Comment by ababic** [comment]
So, I guess my first question is, is it a requirement that form handling itself is done via `fobi.integration.processors.IntegrationProcessor`? And if so, what would be your preferred approach for adding additional items to the context?

**Comment by barseghyanartur** [comment]
@ababic:

Firstly - thanks for support!

It's preferred (remember: DRY). It worked fine with DjangoCMS, FeinCMS and Mezzanine integration.

Look, for instance here it's done as follows:

- https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/apps/djangocms_integration/cms_plugins.py#L42

- https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/apps/feincms_integration/widgets.py#L92

- https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/apps/mezzanine_integration/page_processors.py#L30

So, the internal method `_process` either does everything for you.

But, if wagtail is different you are free to do it the way it's done in wagtail. I'll probably make some modifications later to make it as DRY as possible.

**Comment by ababic** [comment]
Hi @barseghyanartur. Am i correct in thinking that the `form_template_name` should just be responsible for rendering the 'form' part in a view, which can then be output anywhere in a custom template?

And does that differ for the `success_page_template_name` field? Is that template supposed to be responsible for rendering the entire page/view?

Thanks

**Comment by barseghyanartur** [comment]
@ababic:

Check this:

- https://github.com/barseghyanartur/django-fobi/blob/master/examples/simple/settings/base.py#L412

- https://github.com/barseghyanartur/django-fobi/tree/master/examples/simple/templates/fobi/bootstrap3_extras

**Comment by dwasyl** [comment]
@ababic Did you ever get anywhere with Wagtail integration? I'm hitting a wall with wagtailforms and this would be a great way to get around that.

**Comment by barseghyanartur** [comment]
@dwasyl:

FYI, contributions are much appreciated. I don't have wagtail experience and at the moment I'm too much busy with resurrection of another package of mine (``django-dash``), which I left unmanaged way too long. Thus, I don't have time for it yet (unless it arrives as a sponsored feature request).

**Comment by gfranxman** [comment]
Fobi is pretty incredible.    I'm also looking to use it with wagtail and am willing to help.  It looks like this has stalled.    What's the best way to get started?

**Comment by barseghyanartur** [comment]
@gfranxman:

I'm gonna do a tiny release today and then I'll sync the [wagtail/integration](https://github.com/barseghyanartur/django-fobi/tree/wagtail/integration) branch with master.

Do you have wagtail experience? Some work has already been done (although you may throw it all away, if you think it doesn't make sense). 

Just as in case of DjangoCMS or FeinCMS, the contrib package should provide plugins for integration with CMS. It may have templates as well, although not necessarily. 

There should be a working example. In case of DjangoCMS and FeinCMS I integrated it inside the [simple](https://github.com/barseghyanartur/django-fobi/tree/master/examples/simple) project. In case of Mezzanine, the changes were too much, so I use a dedicated [mezzanine_example](https://github.com/barseghyanartur/django-fobi/tree/master/examples/mezzanine_example) project.

I seemed to me it makes sense to do the same with wagtail.

**Comment by barseghyanartur** [comment]
@gfranxman:

I have also included [wagtaildemo](https://github.com/barseghyanartur/django-fobi/tree/wagtail/integration/examples/wagtaildemo) integration project, which I started on about a half year ago.

**Comment by barseghyanartur** [comment]
@gfranxman:

FYI, I'm almost done with wagtail integration. Do you think you could take over the testing part?

**Comment by barseghyanartur** [comment]
@ababic:

Thank you! Your code was a good starting point.

**Comment by gfranxman** [comment]
yeah, yeah!

**Comment by barseghyanartur** [comment]
@gfranxman:

The [wagtail/integration](https://github.com/barseghyanartur/django-fobi/tree/wagtail/integration) branch seems to work for me.

See the git-submodule `wagtaildemo`.

Wagtail demo seems to be based on bootstrap3, so I used bootstrap3 theme there as well.

See the screen-shots below.

**Fobi form page view**

![fobi_form_page_wagtail_demo_-_2017-06-15_02 14 01](https://user-images.githubusercontent.com/4925587/27159867-6d95a3e0-5170-11e7-9ab7-00a8e4b9ccda.png)

**Fobi form submitted view**
![fobi_form_page_wagtail_demo_-_2017-06-15_02 14 19](https://user-images.githubusercontent.com/4925587/27159873-72744f10-5170-11e7-87b1-36b3a5640ecb.png)

**Wagtail admin - fobi form page edit view**
![wagtail_-_editing_fobi_form_page_fobi_form_page_-_2017-06-15_02 16 06](https://user-images.githubusercontent.com/4925587/27159927-c3f4d544-5170-11e7-8f1c-3519b1f4d793.png)

**Wagtail admin - create a page view**
![wagtail_-_create_a_page_in_welcome_to_your_new_wagtail_site _-_2017-06-15_02 16 27](https://user-images.githubusercontent.com/4925587/27159934-d0c93bc0-5170-11e7-9b73-c8a02a1bebe2.png)

**Comment by barseghyanartur** [comment]
@ababic, @dwasyl:

Could you, guys, also do some tests?

**Comment by barseghyanartur** [comment]
Any remarks yet?

**Comment by dwasyl** [comment]
@barseghyanartur I haven't had a chance yet, hoping to give it a go in the next couple of days.

**Comment by ababic** [comment]
@barseghyanartur I've got too much on right now I'm afraid. Trying to get a lot of things tied up before I go on holiday.

**Comment by barseghyanartur** [comment]
I merged this branch into master. Version [0.12](https://pypi.python.org/pypi/django-fobi/0.12) has Wagtail support (yet experimental).

This ticket is closed. Feel free to open a new issue if needed.
