### ISSUE TITLE
Exception when using a dotted path to an AppConfig in INSTALLED_APPS

### ISSUE THREAD

**Issue by thomasWajs** [barseghyanartur/django-fobi#5]
Since django 1.7, it's possible to use a dotted path to an AppConfig class instead of a dotted path to an app top-module.
Example for the admin app, without auto-discovering :
```python
INSTALLED_APPS = (
    'django.contrib.admin.apps.SimpleAdminConfig',
    ...
)
```

In this situation, fobi.discovery.autodiscover.do_discover fail at line 29 
```python
app_path = __import__(app, {}, {}, [app.split('.')[-1]]).__path__
```
```
File "\lib\site-packages\fobi\discover.py", line 29, in do_discover
    app_path = __import__(app, {}, {}, [app.split('.')[-1]]).__path__
ImportError: No module named SimpleAdminConfig
```

**Comment by barseghyanartur** [comment]
@thomasWajs 

Thanks for reporting this. Fixed in version 0.4.24.
