### ISSUE TITLE
In how many days/months are you planning for enhancement of django-rest-framework to this package ?

### ISSUE THREAD

**Issue by jdsinh** [barseghyanartur/django-fobi#58]

**Comment by barseghyanartur** [comment]
@jdsinh:
It depends on priorities. Is sponsored, can be done in a couple of weeks. Otherwise, likely to be done in about half a year.

**Comment by barseghyanartur** [comment]
@jdsinh:

FYI, current plan is to release Django REST framework support until 13th of May.

**Comment by barseghyanartur** [comment]
@jdsinh:

FYI, implemented in version 0.11.
