### ISSUE TITLE
Questions about Django 1.6 support.

### ISSUE THREAD

**Issue by Subaku** [barseghyanartur/django-fobi#59]
Hello,

I've got a production system that's running Django 1.6.10 and I've installed django-fobi 0.9.17 as that's what was stated would still support our version of Django. I'm running into a few issues that I'd like clarification on.

1. Is the db_store form handler not meant for anything less than Django 1.7? It contains models that appear to be needed yet there are no valid south_migrations within that "micro app" although there are migrations for later versions of Django. I had to either comment out `fobi.contrib.plugins.form_handlers.db_store` in my settings or tell South to ignore that app all together. This of course causes errors elsewhere when trying to run the GUI.
2. I understand you've provided a dashboard for managing forms but I was curious if those templates are easily extensible for use in the Django Admin? We use Django Suit for our admin and wish to create forms to attach to our reporting models so I'm trying to make sense of the best way to create forms for that purpose.

Great work here by the way. I love what I see and I appreciate your time!

**Comment by barseghyanartur** [comment]
@Subaku:

1. You will need to create your own migrations for `db_store` plugin, which is very easy (just list your custom migrations in `SOUTH_MIGRATION_MODULES`.

2. For Django admin integration, there's a theme (`simple` theme) and another theme based on `django-admin-style` (see the source) package as an example. That's the shortest way to go if you want to seamlessly integrate `django-fobi` into your existing admin. I never considered to create a dedicated `django-suit` theme, but I could reconsider it if sponsored (just in case if you're lazy to do that yourself but have some spare budget for outsourcing that part).

**Comment by barseghyanartur** [comment]
@Subaku:

Did you manage to solve it? Can I close this issue?

**Comment by Subaku** [comment]
@barseghyanartur:

I've not actually acted on your advice as of yet as my current scope of work has changed. Please feel free to close this ticket. Thank you for your time!

**Comment by barseghyanartur** [comment]
@Subaku:

Closing this. Feel free to reopen any time.
