### ISSUE TITLE
thumbnail is not a valid tag library

### ISSUE THREAD

**Issue by MaximilianKindshofer** [barseghyanartur/django-fobi#6]
I tried to add an Image as form content and it throws me the above error.
I don't have any thumbnail library installed, which one should I choose? Could you add one to the requirements?

**Comment by barseghyanartur** [comment]
@MaximilianKindshofer 

``easy-thumbnails`` is in the requirements (setup_requires).

- https://github.com/barseghyanartur/django-fobi/blob/master/setup.py#L75

**Comment by MaximilianKindshofer** [comment]
Ok my bad... I missed this...

**Comment by barseghyanartur** [comment]
@MaximilianKindshofer 

You actually do have a point. It's not mentioned in the documentation. I'm going to add it. 

Thanks for bringing this up.

**Comment by barseghyanartur** [comment]
@MaximilianKindshofer 

Mentioned in the docs. Thanks!
