### ISSUE TITLE
fobi demo on heroku doesn't send activation e-mail.

### ISSUE THREAD

**Issue by ksze** [barseghyanartur/django-fobi#73]
This is not exactly a problem with fobi per se.

I wanted to try out fobi on the demo site (https://django-fobi.herokuapp.com/). However, I tried to register twice with the same Gmail address and never got an activation e-mail.

**Comment by barseghyanartur** [comment]
@ksze:

Yes, unfortunately, Heroku made it extremely difficult to send emails. Honestly, all solutions available there are paid or require a credit card. There's nothing I could do at the moment.
