### ISSUE TITLE
DB store handler only saves the "display" string of Select fields, but not the "value" string

### ISSUE THREAD

**Issue by ksze** [barseghyanartur/django-fobi#75]
If I specify a gender Select field with the following choices:
```
m,男
f,女
```
I expect the DB store handler to save the gender field as `{"gender": "m"}`, in the `SavedFormDataEntry.saved_data`.

But instead, I see `{"gender": "男"}` （unicode-escaped).

I hesitate to suggest changing what is saved in `SavedFormDataEntry.saved_data` because that would break things for existing installations, but it would certainly make sense to include the "m" or "f" somewhere in `SavedFormDataEntry`.

**Comment by barseghyanartur** [comment]
@ksze:

That's already implemented.

Do the following in your project's settings:

```python
 FOBI_FORM_ELEMENT_SELECT_SUBMIT_VALUE_AS = "mix"
```

[Available choices are "mix", "repr", "val"](https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/constants.py#L47).

Do that for every choice elements.
