### ISSUE TITLE
Wizard edit screens looking broken in `Simple` and `Foundation 5` themes

### ISSUE THREAD

**Issue by philgyford** [barseghyanartur/django-fobi#77]
I've enabled the 'simple' theme, but it looks like something's missing (some CSS maybe?):

![screen shot 2017-07-25 at 10 55 49](https://user-images.githubusercontent.com/66670/28566700-dba0e710-7127-11e7-998a-2ac9883a3cd3.png)

I'm using Django 1.11.3.

My `INSTALLED_APPS` include:

    'fobi',
    'fobi.contrib.themes.simple',
    'fobi.contrib.plugins.form_elements.fields.boolean',
    'fobi.contrib.plugins.form_elements.fields.checkbox_select_multiple',
    'fobi.contrib.plugins.form_elements.fields.text',
    'fobi.contrib.plugins.form_handlers.db_store',

And I have `FOBI_DEFAULT_THEME = 'simple'`.

I've included the edit URLs under `admin/`:

    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^admin/my-forms/', include('fobi.urls.edit')),
        # ...
    ]

**Comment by barseghyanartur** [comment]
Simple theme hasn't been updated since Django 1.8 and there have been updates to the styles of django admin since then. So, it can be considered a "bug" which needs to be solved.

**Comment by philgyford** [comment]
Ah, fair enough, thanks for the clarification!

**Comment by barseghyanartur** [comment]
@philgyford:

Sorry for disinformation. Actually, I never reflected the changes of the wizards functionality in the `simple` theme. Forms look just fine, but some styling is required for the wizards part. Thus, it's certainly a bug, which is going to be addressed ASAP.

**Comment by barseghyanartur** [comment]
FYI, same goes for Foundation 5 theme.

**Comment by barseghyanartur** [comment]
@philgyford:

I have it working locally. You may expect a release one of these days.

**Comment by barseghyanartur** [comment]
@philgyford:

Version [0.12.1](https://pypi.python.org/pypi/django-fobi/0.12.1) contains the fix for the `simple` theme.
