### ISSUE TITLE
JSON Schema support

### ISSUE THREAD

**Issue by zackbleach** [barseghyanartur/django-fobi#78]
I've seen this discussed in different issues/PRs but couldn't find a centralised place to track this. Do you still intend to build in JSON Schema support for the metadata sent back from OPTION requests? 

Given that there are lots of JS libs which will render a schema into a form (including one from Mozilla), I think it makes sense to go with this rather than rolling our own representation of the form. WDYT?

**Comment by barseghyanartur** [comment]
@zackbleach:

It's on the list, but help is appreciated. The initial work has been done in the [drf-json-schema branch](https://github.com/barseghyanartur/django-fobi/tree/drf-json-schema/src/fobi/contrib/apps/drf_integration), but it hasn't been finished yet.

Wanna help? :)

**Comment by zackbleach** [comment]
Sure, have you made any notes on the translations that are required yet?

**Comment by barseghyanartur** [comment]
@zackbleach:

You can use issue #69 as the main source of information.

- [list of all fields](https://github.com/barseghyanartur/django-fobi/issues/69#issuecomment-305107694)
- [current schema](https://github.com/barseghyanartur/django-fobi/issues/69#issuecomment-305347693)

The idea is to provide a custom metadata class. At the moment it's `FobiMetaData`, but it should be customisable (in settings). I'll keep the `FobiMetaData` as default for at least 0.13 (fobi release). If `FobiJSONSchemaMetaData` works well, it will be made the default as per 0.14.

I actually think it makes sense to "merge" this issue with #69. Shall we continue in the #69?

**Comment by zackbleach** [comment]
sg!
