### ISSUE TITLE
Form for adding a content_image form element looks a bit broken when the browser window is wide

### ISSUE THREAD

**Issue by ksze** [barseghyanartur/django-fobi#79]
Just like tht title says. Tried it in Firefox 54.0.1 for Windows. Here is a screenshot:

![image](https://user-images.githubusercontent.com/381556/29110795-81a0748e-7d1a-11e7-8132-ab82025f407a.png)

As you can see, the label ends up *after* the input element of the *previous* field. E.g. the "Fit method" label comes on the same line, after the input box of the "Alt text" field.

**Comment by barseghyanartur** [comment]
@ksze:

Could you, please, verify if this works fine for you?

https://django-fobi.herokuapp.com/en/fobi/forms/elements/add/1473/content_image/

**Comment by ksze** [comment]
@barseghyanartur 
I don't have a working account there because the last two time I tried to register, you ran out of e-mail sending quota. And now my account is in a limbo. There's no page to trigger the resending of activation e-mial.

**Comment by barseghyanartur** [comment]
@ksze:

Login credentials are in the Readme and online docs.

**Comment by barseghyanartur** [comment]
@ksze:

Any news on this?

**Comment by ksze** [comment]
I don't see that problem on your test site.

I'll need to do some more tests.

**Comment by barseghyanartur** [comment]
@ksze:

I'm closing this for now. Feel free to request reopening, if needed.

**Comment by ksze** [comment]
Turns out I forgot to add some css classes when inheriting the templates. So this is indeed invalid.
