### ISSUE TITLE
Broken link in documentations

### ISSUE THREAD

**Issue by MJafarMashhadi** [barseghyanartur/django-fobi#80]
I wanted to edit the file rightaway and make a pull request but Github did not allow me to do that for some reason.

In [This part](http://django-fobi.readthedocs.io/en/0.11.13/#path-to-sample-textarea-forms-py) of the docs there's a link to an [example](https://github.com/barseghyanartur/django-fobi/blob/stable/src/fobi/contrib/plugins/form_elements/content/image/forms.py) which is broken. The correct url seems to be the following:

https://github.com/barseghyanartur/django-fobi/blob/stable/src/fobi/contrib/plugins/form_elements/content/content_image/forms.py

**Comment by barseghyanartur** [comment]
@MJafarMashhadi:

Thanks for reporting this. I'll fix it in the next release.

**Comment by barseghyanartur** [comment]
Fixed in [0.12.3](https://pypi.python.org/pypi/django-fobi/0.12.3).
