### ISSUE TITLE
Django 1.11 context problem

### ISSUE THREAD

**Issue by phiron** [barseghyanartur/django-fobi#83]
Hello,

I Has a problem with django 1.11:

> 
> Request Method: | GET
> -- | --
> http://localhost:9000/fobi/
> 1.11.4
> ModuleNotFoundError
> No module named 'django.template.context_processors.requestfobi'; 'django.template.context_processors' is not a package
> /home/caaorg/virtual-caaorg/lib/python3.6/importlib/__init__.py in import_module, line 126
>

**Comment by barseghyanartur** [comment]
@phiron:

Check your settings. 

There isn't such a context processor `django.template.context_processors.requestfobi`. 

There is `django.template.context_processors.request`.

**Comment by phiron** [comment]
@barseghyanartur Thanks for reply

In my settings does not has this option, I did exactly as here: http://pythonhosted.org/django-fobi/quickstart.html

The problem occurs when I put: "fobi.context_processors.theme",   in  'context_processors': [] list

In Django 1.11 does not exists the option TEMPLATE_CONTEXT_PROCESSORS

I think the problem is there.

**Comment by phiron** [comment]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # insert your TEMPLATE_DIRS here
            TEMPLATE_DIRS_,
        ],
        'OPTIONS': {
            'debug':DEBUG,
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.request",
                "utilitarios.contextos.cod_facebook",
                "utilitarios.contextos.redes_sociais",
                "utilitarios.contextos.google_analytics",
                "utilitarios.contextos.banner_padrao",
                "utilitarios.contextos.textura",
                "utilitarios.contextos.hotsite_atual",
                "utilitarios.contextos.ultimo_edital",
                "utilitarios.contextos.subprojeto_atual",
                "utilitarios.contextos.projeto_atual",
                "utilitarios.contextos.notificacoes",
                'django.template.context_processors.request'
                #FOBI
                "fobi.context_processors.theme",  # Obligatory
                "fobi.context_processors.dynamic_values",  # Optional
                #FOBI
            ],
            'loaders': [
                # insert your TEMPLATE_LOADERS here
                ('django.template.loaders.cached.Loader', [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },

    },
]

**Comment by barseghyanartur** [comment]
@phiron:

For Django 1.11 see [this](https://github.com/barseghyanartur/django-fobi/blob/master/examples/simple/settings/base.py#L132).
