### ISSUE TITLE
pypi package contains extra wagtail_integration_ folder

### ISSUE THREAD

**Issue by minusf** [barseghyanartur/django-fobi#89]
when installing fobi using `pip`, there is an extra `./contrib/apps/wagtail_integration_` folder
(notice the trailing `_`)

**Comment by barseghyanartur** [comment]
@minusf:

Ah, thanks. That was old WIP app. I'll remove it in upcoming releases.

**Comment by barseghyanartur** [comment]
Solved in 0.12.6.
