### ISSUE TITLE
Mail plugin data format

### ISSUE THREAD

**Issue by tsbarnes** [barseghyanartur/django-fobi#9]
Is there a way to make the mail handler display model objects by their string representation instead of as `app.model.id` like it does by default?  I've noticed on models that have the `__str__` method it will append it (like `app.model.id.str`) but it would be nice to have it just use the string.

**Comment by barseghyanartur** [comment]
@tsbarnes 

Of course there is. You should locally override the ``select_model_object`` plugin and force-register it. All the plugins (form elements, handlers, themes) can be overridden that way.

https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_elements/fields/select_model_object/fobi_form_elements.py#L66

yourproject/yourapp/fobi_form_elements.py
-----------------------------------------
from fobi.helpers import safe_text
from fobi.contrib.plugins.form_elements.fields.select_model_object.fobi_form_elements import MySelectModelObjectInputPlugin

class MySelectModelObjectInputPlugin(SelectModelObjectInputPlugin):
    def submit_plugin_form_data(self, form_entry, request, form):
        """
        Submit plugin form data/process.
        :param fobi.models.FormEntry form_entry: Instance of
            ``fobi.models.FormEntry``.
        :param django.http.HttpRequest request:
        :param django.forms.Form form:
        """
        # Get the object
        obj = form.cleaned_data.get(self.data.name, None)
        if obj:
            # Handle the submitted form value
            value = '{0}'.format(safe_text(obj))

            # Overwrite ``cleaned_data`` of the ``form`` with object qualifier.
            form.cleaned_data[self.data.name] = value

        # It's critically important to return the ``form`` with updated
        # ``cleaned_data``
        return form


form_element_plugin_registry.register(MySelectModelObjectInputPlugin, force=True)

**Comment by barseghyanartur** [comment]
@tsbarnes 

Did it help?

**Comment by barseghyanartur** [comment]
@tsbarnes 

FYI, it's now (partly) implemented in the 0.4.27 for `radio`, `select` and `select_multiple` (not yet properly documented, see the changelog https://github.com/barseghyanartur/django-fobi/blob/master/CHANGELOG.rst). Implementation for `select_model_object` and `select_multiple_model_objects` is planned in 0.4.28.

**Comment by barseghyanartur** [comment]
@tsbarnes 

Completely solved in 0.4.28. See the changelog https://github.com/barseghyanartur/django-fobi/blob/master/CHANGELOG.rst) and updated documentation.
