### ISSUE TITLE
Make new content (presentational) rich text plugin

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-fobi#99]
Make new content (presentational) rich text plugin (a modern WYSIWYG).

TODOs left:

- [x] Add correspondent Django REST Framework integration plugin for the new ``content_richtext`` plugin.
- [x] Add new widget for ``content_richtext`` plugin for Bootstrap3 theme
- [x] Add new widget for ``content_richtext`` plugin for Foundation5 theme
- [x] Add new widget for ``content_richtext`` plugin for Simple theme
- [x] Add new widget for ``content_richtext`` plugin for DjangoCMS admin theme.

**Comment by barseghyanartur** [comment]
@minusf:

Interested?

**Comment by barseghyanartur** [comment]
@minusf:

Any progress on WYSIWYG?

**Comment by minusf** [comment]
sorry, some other stuff got in the way. WIP.

**Comment by barseghyanartur** [comment]
@minusf:

Hey, I have it working with no problems. Check the master branch. I replaced SummerNote with CKEditor (django-ckeditor) though.

![screenshot from 2017-12-15 22-43-01](https://user-images.githubusercontent.com/4925587/34061652-701a8e3c-e1e9-11e7-8652-22f3352aa53b.png)

**Comment by barseghyanartur** [comment]
@minusf:

See the TODOs (see the top of the thread), in case you want to help.

**Comment by barseghyanartur** [comment]
Implemented in [0.12.7](https://pypi.python.org/pypi/django-fobi/0.12.7).
